from enum import StrEnum


class ErrorType(StrEnum):

    # Success
    SUC_200_SUCCESS = "SUCCESS"
    SUC_201_RESOURCE_CREATED = "RESOURCE_CREATED"

    # 400
    VAL_400_VALIDATION_ERROR = "VALIDATION_ERROR"
    VAL_400_INVALID_INPUT = "INVALID_INPUT"

    # 401
    AUTH_401_INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    AUTH_401_TOKEN_EXPIRED = "TOKEN_EXPIRED"
    AUTH_401_UNAUTHORIZED = "UNAUTHORIZED"
    AUTH_401_INVALID_TOKEN = "INVALID_TOKEN"
    AUTH_401_SESSION_INVALID = "SESSION_INVALID"

    # 403
    AUTH_403_ACCESS_DENIED = "ACCESS_DENIED"

    # 404
    RES_404_NOT_FOUND = "NOT_FOUND"

    # 409
    CON_409_CONFLICT_ERROR = "CONFLICT_ERROR"

    # 404
    RES_404_USER_NOT_FOUND = "USER_NOT_FOUND"

    # 500
    SYS_500_INTERNAL_ERROR = "INTERNAL_SERVER_ERROR"